### ISSUE TITLE
2019年06月開催 LT 会

### ISSUE THREAD

**Issue by IkezoeMakoto** [hacker-s-gate/events#9]
次回は 6 月目安

**Comment by okashoi** [comment]
## 決定事項

* 開催日次
    * 2019年06月19日（水）
* 形式
    * LT 会
* テーマ
    * コードの書き方のこだわり（名称仮）
        * 例）コーディングスタイル（ハードタブ／ソフトタブ）、エディタ設定、周辺機器（キーボードなど）
* 会場
    * 株式会社ウィルゲート Room0

## TODO

一旦書き出したら issue に起こし~ます（粒度・階層も整理）~ ました。

また、このテンプレを別途ファイルにして PR 出します。

- [ ] connpass ページ作成
    - [ ] 枠ごとの参加人数上限
    - [ ] イベント名
    - [ ] イベント概要
    - [ ] タイムスケジュール
    - [ ] アイキャッチ
    - [ ] 参加者事前アンケート（あれば）
    - [ ] 運営メンバー・社員は connpass に登録するのか否か
- [ ] 宣伝（全員で）
    - [ ] SNS・知人に直接・所属コミュニティ等
        - [ ] 開催直後
        - [ ] 定期
        - [ ] 直前
    - [ ] 社内（拡散のお願い）
        - [ ] slack
        - [ ] 朝礼
- [ ] 事前準備
    - [ ] 利用備品の申請（詳細は会社の Conluence に記載）
    - [ ] 稟議&事前申請（詳細は会社の Conluence に記載）
    - [ ] 飲食物の手配
    - [ ] 開会のスライド準備
    - [ ] 参加者アンケート準備
    - [ ] 配信準備（やるなら）
    - [ ] 当日の役割分担ぎめ（協力してくれる人集め）
        - [ ] 音楽流す人
        - [ ] 司会進行
        - [ ] タイムキーパー
        - [ ] 受付
        - [ ] 会場設営
        - [ ] 片付け
        - [ ] SNS 実況
        - [ ] 20:00 以降到着／離脱の人の案内
    - [ ] 当日の段取りを事前確認（別途テンプレ作成）
- [ ] 連絡等
    - [ ] 参加者へのリマインダ（connpass から）
    - [ ] 社内に Room0 専有の連絡
    - [ ] イベント情報をイベント開催履歴スプレッドシートに記載
- [ ] 開催後
    - [ ] 経費精算（詳細は会社の Conluence に記載）
    - [ ] イベント開催履歴スプレッドシートの集客実績情報更新 
    - [ ] ブログ（テックブログ公開のフローに準ずる）
        - [ ] ブログ記事を connpass に貼る
    - [ ] 発表者に資料を connpass にアップしてもらう

**Comment by okashoi** [comment]
必要そうな issue は一通り切った

当日の段取りは別途テンプレを準備します。

**Comment by okashoi** [comment]
これ、あらかじめテンプレ作っておいて Project 作成時に一括で issue 作成、みたいなのできないかな？

**Comment by 8845musign** [comment]
バナー作りたいです

**Comment by okashoi** [comment]
@8845musign ありがとうございます！バナー作単体で issue 切ってアサインしておきますー

**Comment by okashoi** [comment]
@8845musign この Organization への招待を送ったので、参加していただけると！（それまでアサインができない）

**Comment by cocoeyes02** [comment]
> 利用備品の申請
> 稟議&事前申請

> 飲み物の手配
> 参加者アンケート準備
> 経費精算

この辺やりたいです〜

**Comment by okashoi** [comment]
@cocoeyes02 立候補ありがとう！アサインしました！

その中だと最初に着手すべきは稟議出すことですね（詳細は社の slack で共有します）

**Comment by 8845musign** [comment]
@okashoi 
ジョインしました！

**Comment by IkezoeMakoto** [comment]
プロジェクトに優先度がほしい気がする。。結構タスク多いと思うんだけど、どれが緊急で対応しないと行けないかがわからない。

やるならラベルで表現すればいいかな、、？

**Comment by okashoi** [comment]
ラベルよさそう

**Comment by okashoi** [comment]
段階どうしよう、というのはあるけどいったん

「優先度：高」
「緊急度：高」

は作った

運用は決めてない

**Comment by IkezoeMakoto** [comment]
いいね！

これで緊急度が高いもの、優先度が高いものでまだ動いてないものを確認していけば良さそう

**Comment by IkezoeMakoto** [comment]
受付のやることを整理する

**Comment by okashoi** [comment]
関連する全ての Issue が close されたので こちらも close します。
